artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Rajatgoel179/gg/raw/main/newdata.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/newdata.csv



  